/**
 * Store Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { When } from '../models/When';
import { HttpFile } from '../http/http';

export class PotentialCustomer {
    'id': number;
    'name': string;
    'email': string;
    'message': string;
    'when'?: When;
    'serviceId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "when",
            "baseName": "when",
            "type": "When",
            "format": ""
        },
        {
            "name": "serviceId",
            "baseName": "service_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PotentialCustomer.attributeTypeMap;
    }

    public constructor() {
    }
}

