/**
 * Store Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Value } from '../models/Value';
import { HttpFile } from '../http/http';

export class ServiceCatalogInput {
    'id': number;
    'photo': string;
    'name': string;
    'description': string;
    'when': Date;
    'value': Value;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "photo",
            "baseName": "photo",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "when",
            "baseName": "when",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Value",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServiceCatalogInput.attributeTypeMap;
    }

    public constructor() {
    }
}

